"""Export debate data as Markdown or JSON."""

from __future__ import annotations

import json
from datetime import datetime


def export_markdown(state: dict) -> str:
    """Generate a complete Markdown debate transcript."""
    lines = []
    problem = state.get("problem", "Unknown")
    score_history = state.get("score_history", [])
    proposals = state.get("proposals", [])

    # Header
    winner = "TBD"
    final_p = final_a = 0.0
    if score_history:
        last = score_history[-1]
        final_p = last.get("proposer_score", 0)
        final_a = last.get("adversary_score", 0)
        winner = "Proposer" if final_p > final_a else "Adversary" if final_a > final_p else "Tie"

    lines.append(f"# Architecture Debate: {problem[:80]}")
    lines.append(f"**Date:** {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    lines.append(f"**Rounds:** {state.get('round', 0)} | **Winner:** {winner} | **Final:** {final_p:.2f} vs {final_a:.2f}")
    lines.append("")

    # Interview
    enriched = state.get("enriched_context", "")
    if enriched:
        lines.append("## Interview")
        lines.append(enriched)
        lines.append("")

    # Rounds
    rounds_seen = sorted(set(p["round"] for p in proposals))
    for r in rounds_seen:
        lines.append(f"## Round {r}")
        round_proposals = [p for p in proposals if p["round"] == r]
        round_score = next((s for s in score_history if s["round"] == r), None)

        for p in round_proposals:
            agent = p["agent"].title()
            model = p.get("model", "")
            score = f" — Score: {p['score']:.2f}" if p.get("score") is not None else ""
            lines.append(f"### {agent} ({model}){score}")
            lines.append(p.get("solution", ""))
            lines.append("")

        if round_score:
            lines.append(f"**Round {r} Scores:** Proposer {round_score['proposer_score']:.2f} | "
                         f"Adversary {round_score['adversary_score']:.2f} | "
                         f"Delta: {round_score['delta']:+.2f}")
            lines.append("")

    # HITL history
    hitl_history = state.get("hitl_history", [])
    if hitl_history:
        lines.append("## HITL Interactions")
        for h in hitl_history:
            lines.append(f"**Round {h.get('round', '?')}:** {h.get('question', '')}")
            lines.append(f"**Answer:** {h.get('answer', '')}")
            lines.append("")

    lines.append("---")
    lines.append(f"*Generated by Archie — AI Solution Architect Debate*")

    return "\n".join(lines)


def export_json(state: dict) -> str:
    """Dump the full debate state as JSON."""

    def _serialize(obj):
        if isinstance(obj, (set, frozenset)):
            return list(obj)
        if hasattr(obj, "isoformat"):
            return obj.isoformat()
        raise TypeError(f"Object of type {type(obj)} is not serializable")

    return json.dumps(state, indent=2, default=_serialize)
